### ISSUE TITLE
receiver type CALayer

### ISSUE THREAD

**Issue by keithics** [sweetmandm/FontAwesomeTools-iOS#1]
simple fix was to import QuartzCore/QuartzCore.h

![screen shot 2013-12-17 at 7 07 48 pm](https://f.cloud.github.com/assets/229427/1763350/8dbdac42-670b-11e3-89f0-d78f8329a417.png)

**Comment by sweetmandm** [comment]
sorry, you need to add the QuartzCore framework to your project and <code>#import &lt;QuartzCore/QuartzCore.h&gt;</code>. I'll fix this in a future commit

**Comment by keithics** [comment]
no problem, thanks.
